# Graduate Rotational Internship Program @The Sparks Foundation
## **Author** : **Abhiram K M**
### **Task 1** : Object Detection

* *Description : Implement an object detector which identifies the classes of the objects in an image or video*

In [1]:
#importing opencv and numpy modules
import cv2
import numpy as np

In [2]:
#declaring thresholds
whT = 320
confThreshold = 0.5

In [3]:
#loading coco names containing the objects
className = []
with open('coco.names', 'rt') as f:
    classNames = f.read().rstrip('\n').split('\n')

In [4]:
#loading the yolo weights and configuration files
model_cfg = 'yolov3.cfg'
model_weights = 'yolov3.weights'

In [5]:
#setting opencv as backend and target as cpu
net = cv2.dnn.readNet(model_cfg, model_weights)
net.setPreferableBackend(cv2.dnn.DNN_BACKEND_OPENCV)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_CPU)

In [6]:
#function for object detection 
def findObjects(output, img):
    hT, wT, cT = img.shape
    bbox = []
    classIds = []
    confs = []

    for output in outputs:
        for det in output:
            scores = det[5:]
            classId = np.argmax(scores)
            confidence = scores[classId]
            if confidence > confThreshold:
                w, h = int(det[2]*wT), int(det[3]*hT)
                x, y = int((det[0]*wT)-w/2), int((det[1]*hT)-h/2)
                bbox.append([x, y, w, h])
                classIds.append(classId)
                confs.append(float(confidence))

    indices = cv2.dnn.NMSBoxes(bbox, confs, confThreshold, nms_threshold=0.3)
    print(indices)
    for i in indices:
        i = i[0]
        box = bbox[i]
        x, y, w, h = box[0], box[1], box[2], box[3]
        cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 255), 2)
        cv2.putText(img, f'{classNames[classIds[i]].upper()} {int(confs[i]*100)}%',
                    (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 255), 2)

In [7]:
#opencv code for loading video
cap = cv2.VideoCapture('video.mp4')
while True :
    success, img = cap.read()
    blob = cv2.dnn.blobFromImage(img, 1/255, (whT, whT), [0, 0, 0], 1, crop= False)
    net.setInput(blob)

    layerNames = net.getLayerNames()
    outNames = [layerNames[i[0]-1] for i in net.getUnconnectedOutLayers()]
    print(outNames)
    
    outputs = net.forward(outNames)
    findObjects(outputs, img)

    cv2.imshow('image', img)
    if cv2.waitKey(1) == 27:
        break

cap.release()
cv2.destroyAllWindows()

['yolo_82', 'yolo_94', 'yolo_106']
[[1]
 [0]
 [2]
 [3]
 [6]]
['yolo_82', 'yolo_94', 'yolo_106']
[[1]
 [0]
 [2]
 [3]
 [6]]
['yolo_82', 'yolo_94', 'yolo_106']
[[1]
 [0]
 [2]
 [3]
 [6]]
['yolo_82', 'yolo_94', 'yolo_106']
[[1]
 [0]
 [2]
 [6]
 [3]]
['yolo_82', 'yolo_94', 'yolo_106']
[[1]
 [0]
 [2]
 [6]
 [3]
 [7]]
['yolo_82', 'yolo_94', 'yolo_106']
[[1]
 [0]
 [2]
 [6]
 [3]
 [7]]
['yolo_82', 'yolo_94', 'yolo_106']
[[1]
 [0]
 [2]
 [6]
 [3]
 [7]]
['yolo_82', 'yolo_94', 'yolo_106']
[[1]
 [0]
 [2]
 [6]
 [3]
 [7]]
['yolo_82', 'yolo_94', 'yolo_106']
[[1]
 [0]
 [2]
 [6]
 [3]
 [7]]
['yolo_82', 'yolo_94', 'yolo_106']
[[1]
 [0]
 [2]
 [6]
 [7]
 [3]]
['yolo_82', 'yolo_94', 'yolo_106']
[[1]
 [0]
 [2]
 [6]
 [3]
 [7]]
['yolo_82', 'yolo_94', 'yolo_106']
[[1]
 [0]
 [2]
 [6]
 [3]
 [7]]
['yolo_82', 'yolo_94', 'yolo_106']
[[1]
 [0]
 [2]
 [6]
 [3]
 [7]]
['yolo_82', 'yolo_94', 'yolo_106']
[[1]
 [0]
 [2]
 [6]
 [3]
 [7]]
['yolo_82', 'yolo_94', 'yolo_106']
[[1]
 [0]
 [2]
 [6]
 [3]
 [7]]
['yolo_82', 'yolo_94', 'yolo_1